events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://mcp-server:8001;

            access_log /dev/stdout;
            error_log /dev/stderr;
        }
    }
}